[tool.poetry]
name = "habbits"
version = "0.1.0"
description = "Habit Tracker backend with Telegram and Celery"
authors = ["saya <skysaika@yandex.ru>"]
readme = "README.md"
package-mode = false  # отключает установку проекта как пакета

[tool.poetry.dependencies]
python = "^3.13"
django = ">=5.2.3,<6.0.0"
pillow = ">=11.2.1,<12.0.0"
psycopg2-binary = ">=2.9.10,<3.0.0"
python-dotenv = ">=1.1.1,<2.0.0"
ipython = ">=9.3.0,<10.0.0"
djangorestframework = ">=3.16.0,<4.0.0"
drf-spectacular = ">=0.28.0,<0.29.0"
celery = ">=5.5.3,<6.0.0"
redis = ">=6.2.0,<7.0.0"
requests = ">=2.32.4,<3.0.0"
djangorestframework-simplejwt = ">=5.5.0,<6.0.0"
django-cors-headers = ">=4.7.0,<5.0.0"
django-celery-beat = ">=2.8.1,<3.0.0"
drf-yasg = ">=1.21.10,<2.0.0"
gunicorn = "^23.0.0"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
flake8 = "^7.3.0"
isort = "^6.0.1"
pytest = "^8.4.1"
pytest-django = "^4.11.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"