# Generated by Django 5.2.3 on 2025-06-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="ID в телеграме",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tg_username",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Имя в телеграме",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="почта"),
        ),
    ]
