# Generated by Django 5.2.3 on 2025-06-29 17:53

import app_users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0002_remove_user_username_user_tg_chat_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["email"],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", app_users.models.UserManager()),
            ],
        ),
    ]
